### ISSUE TITLE
Swift Package Manager builds for macOS are broken

### ISSUE THREAD

**Issue by markavitale** [microsoft/fluentui-apple#1701]
### Environment Information

- **Platform**:
  - [ ] iOS
  - [x] macOS
- **Package version(s)**: Swift Package Manager - works in release version 0.12, broken in versions 0.13-0.16
- **Xcode and OS versions**: macOS 13.2.1, Xcode 14.3

### Please provide a reproduction of the bug:

cd into the fluentui-apple directory and run `swift build`

#### Actual behavior:
```
% swift build
warning: 'fluentui-apple': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /.../fluentui-apple/ios/FluentUI/TextField/TextField.resources.xcfilelist
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/.../fluentui-apple/macos/FluentUI/Core/FluentUIResources.swift:8:8: error: no such module 'FluentUIResources'
import FluentUIResources
       ^
/.../fluentui-apple/macos/FluentUI/Core/FluentUIResources.swift:8:8: error: no such module 'FluentUIResources'
import FluentUIResources
       ^
/.../fluentui-apple/macos/FluentUI/Core/FluentUIResources.swift:8:8: error: no such module 'FluentUIResources'
import FluentUIResources
       ^
[3/4] Compiling FluentUI_macos FluentUIResources.swift
```

then after fixing that
```
 % swift build
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:189:51: error: cannot find 'FluentUI' in scope
                static let accentBackgroundColor: Color = Color(FluentUI.Colors.primaryTint30)
                                                                ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:190:51: error: cannot find 'FluentUI' in scope
                static let accentForegroundColor: Color = Color(FluentUI.Colors.primaryShade20)
                                                                ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:192:51: error: cannot find 'FluentUI' in scope
                static let subtleForegroundColor: Color = Color(FluentUI.Colors.primary)
                                                                ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:193:52: error: cannot find 'FluentUI' in scope
                static let neutralBackgroundColor: Color = Color(FluentUI.Colors.Palette.gray100.color)
                                                                 ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:194:52: error: cannot find 'FluentUI' in scope
                static let neutralForegroundColor: Color = Color(FluentUI.Colors.Palette.gray900.color)
                                                                 ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:189:51: error: cannot find 'FluentUI' in scope
                static let accentBackgroundColor: Color = Color(FluentUI.Colors.primaryTint30)
                                                                ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:190:51: error: cannot find 'FluentUI' in scope
                static let accentForegroundColor: Color = Color(FluentUI.Colors.primaryShade20)
                                                                ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:192:51: error: cannot find 'FluentUI' in scope
                static let subtleForegroundColor: Color = Color(FluentUI.Colors.primary)
                                                                ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:193:52: error: cannot find 'FluentUI' in scope
                static let neutralBackgroundColor: Color = Color(FluentUI.Colors.Palette.gray100.color)
                                                                 ^~~~~~~~
/.../fluentui-apple/macos/FluentUI/Notification/NotificationBarView.swift:194:52: error: cannot find 'FluentUI' in scope
                static let neutralForegroundColor: Color = Color(FluentUI.Colors.Palette.gray900.color)
                                                                 ^~~~~~~~
[3/4] Compiling FluentUI_macos NotificationBarView.swift
```

#### Expected behavior:

Package builds successfully

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/applications affected: Anything consuming fluentui-apple on macOS via Swift Package Manager
